site_name: Sherpa.ai Federated Learning Framework
docs_dir: sources
extra_css:
  - stylesheets/fonts.css
  - stylesheets/sherpa.css
extra_javascript:
  - js/sherpa.js
theme:
  name: "material"
extra_css:
  - stylesheets/sherpa.css
  - stylesheets/fonts.css
plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Private:
      - Overview: private/overview.md
      - DataNode: private/data_node.md
      - Data: private/data.md
      - Query: private/query.md
      - Federated Operation: private/federated_operation.md
      - Federated Attack: private/federated_attack.md
      - Reproducibility: private/reproducibility.md
  - Databases: databases.md
  - Data Distribution: data_distribution.md
  - Model: model.md
  - Federated Aggregator: federated_aggregator.md
  - Federated Government: federated_government.md
  - Differential Privacy:
      - Mechanisms: differential_privacy/mechanisms.md
      - Sensitivity Sampler: differential_privacy/sensitivity_sampler.md
      - Norm: differential_privacy/norm.md
      - Probability Distribution: differential_privacy/probability_distribution.md
      - Composition: differential_privacy/composition.md
      - Sampling: differential_privacy/sampling.md
